spring:
  datasource:
    url: jdbc:mysql://localhost:3306/staffjoy_account?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: 123456
  jpa:
    show-sql: true
server:
  port: 8081
staffjoy:
  email-service-endpoint: http://localhost:8083
  company-service-endpoint: http://localhost:8082
  bot-service-endpoint: http://localhost:8087
management:
  endpoints:
    web:
      exposure:
        include: "*"
