server:
  port: 80

zuul:
  routes:
    account:
      path: /v1/account/**
      url: http://localhost:8081
    web:
      path: /web
      url: http://localhost:8086
    company:
      path: /v1/company/**
      url: http://localhost:8082