server:
  port: 8083
  servlet:
    context-path: /mail
staffjoy:
  email-service-endpoint: http://localhost:8083
  company-service-endpoint: http://localhost:8082
  bot-service-endpoint: http://localhost:8087
management:
  endpoints:
    web:
      exposure:
        include: "*"
